apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build
spec:
  params:
    - name: REPO_URL
      type: string
  steps:
    - name: checkout
      image: alpine
      script: |
        #!/bin/bash
        git clone $(params.REPO_URL) /workspace/source

    - name: install
      image: node
      script: |
        #!/bin/bash
        cd /workspace/source
        npm install

    - name: test
      image: node
      script: |
        #!/bin/bash
        cd /workspace/source
        npm test
