kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: Developer
  namespace: dev # TODO: Re-run this file with other necessary ns
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
# TODO:
# target all resources with full access
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: Developer
  namespace: staging # TODO: Re-run this file with other necessary ns
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
# TODO:
# target all resources with full access
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: Developer
  namespace: prod  # TODO: Re-run this file with other necessary ns
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
# TODO:
# target all resources with full access
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: DeveloperBinding
  namespace: dev # TODO: Re-run this file with other necessary ns, match with role above
subjects:
- kind: User
  name: Joey
  apiGroup: rbac.authorization.k8s.io
# TODO: add Joey as target user
# note: this is case sensitive
roleRef:
  kind: Role
  name: Developer
  apiGroup: rbac.authorization.k8s.io
# TODO: add target role to Developer
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: DeveloperBinding
  namespace: staging # TODO: Re-run this file with other necessary ns, match with role above
subjects:
- kind: User
  name: Joey
  apiGroup: rbac.authorization.k8s.io
# TODO: add Joey as target user
# note: this is case sensitive
roleRef:
  kind: Role
  name: Developer
  apiGroup: rbac.authorization.k8s.io
# TODO: add target role to Developer
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: DeveloperBinding
  namespace: prod # TODO: Re-run this file with other necessary ns, match with role above
subjects:
- kind: User
  name: Joey
  apiGroup: rbac.authorization.k8s.io
# TODO: add Joey as target user
# note: this is case sensitive
roleRef:
  kind: Role
  name: Developer
  apiGroup: rbac.authorization.k8s.io
# TODO: add target role to Developer