kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: Intern
  namespace: dev
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: InternBinding
  namespace: dev
subjects:
- kind: User
  name: Jules
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: Intern
  apiGroup: rbac.authorization.k8s.io